### ISSUE TITLE
Boosts activities from other *local* users dont appear in the notification feed

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#1222]

**Comment by mayel** [comment]
backend and UI tests pass but seems to not work in the browser?

**Comment by mayel** [comment]
Maybe the way I refactored the creator functions broke it, sorry

**Comment by ivanminutillo** [comment]
fixed

**Comment by mayel** [comment]
how is that related? I thought we were getting the creator using preload_creator and object_creator in Objects?

**Comment by mayel** [comment]
because we preload the creator using maybe_preload_creator and maybe_join_creator but with optimisations which this disables

**Comment by mayel** [comment]
actually boost notifications still not working for me in browser
