### ISSUE TITLE
MacOS Dev Setup Incompatibility

### ISSUE THREAD

**Issue by harveypitt** [bonfire-networks/bonfire-app#1670]
**Describe the bug**
New users attempting to set up the development environment on macOS following the "Hacking" guide are unable to launch the application. The process fails due to three distinct blocking issues: a Bash syntax incompatibility in helper scripts, invalid version numbers in the `.tool-versions` file causing Docker build failures, and a compilation error in `bonfire_common` related to `ex_cldr`.

**To Reproduce**
1. Clone the `bonfire` repository on a macOS system.
2. Follow the [Hacking guide instructions](https://docs.bonfirenetworks.org/hacking.html).
3. Run `just setup-dev`.
4. See error messages:
   - `tool-versions-to-env.sh: line 75: ${full_key^^}=${value}: bad substitution`
   - `failed to solve: hexpm/elixir:1.19.4...: not found` (Docker build failure)
   - `could not compile dependency :bonfire_common, "mix compile" failed` (ex_cldr KeyError)

**Expected behavior**
The `just setup-dev` command should execute successfully, configuring the environment variables, building the Docker images with valid tags, and compiling the Elixir dependencies without error.

**Screenshots**
N/A 
**Bonfire environment (please complete the following information):**
- Running env: dev
- Running with Co-op Cloud and/or Docker?: full (Docker Compose)
- Running version: 1.0.1-alpha.9
- Running flavour: social
- Running any extra/forked extensions: none

**Client device (please complete the following information):**
 - Device: Mac
 - OS: macOS (Default Shell: /bin/bash 3.2)
 - Browser: N/A (CLI / Build process)
 - Browser Version: N/A

**Additional context**
1. **Bash Incompatibility**: The `tool-versions-to-env.sh` script utilizes `${var^^}` for uppercase string conversion. This is valid in Bash 4.0+, but macOS ships with Bash 3.2, causing the "bad substitution" error.
2. **Invalid Docker Tags**: The `.tool-versions` file specified versions (Elixir 1.19, Erlang 28) that do not yet exist as tags in the `hexpm/elixir` Docker Hub repository, causing the `docker compose build` step to fail.
3. **Dependency Conflict**: `bonfire_common` failed to compile due to an `ex_cldr` configuration error (`KeyError` regarding `:date_time_at_formats`), which required a dependency update/clean to resolve.

**Comment by mayel** [comment]
Thanks for the report! will look into these

**Comment by mayel** [comment]
I've pushed some updates that should hopefully resolve the ex_cldr issue

**Comment by mayel** [comment]
Could you please paste the just stacktrace of the docker error?

**Comment by mayel** [comment]
I've merged the bash fixes, now remains the docker error

**Comment by ju1m** [comment]
Hi! I don't know if I'm not doing things as expected by calling `extensions/social/install.sh --yes` which then calls `extensions/ember/install.sh --yes`, because that causes the `ex_cldr` error to still occur for me due to [`extensions/ember/install.sh` overriding `config/deps.hex`](https://github.com/bonfire-networks/ember/blob/16e0a95d6ef8c29e0ef20395cd977e4f1c8dff0c/install.sh#L37) hence reverting the fix in [2e189db16e7379bdda6235e107c614ca43d22a7d](https://github.com/bonfire-networks/bonfire-app/commit/2e189db16e7379bdda6235e107c614ca43d22a7d#diff-fdb3d908a3a5071f3b8773118371530d703cb5a09730687dd8b7d78277958c06):

AFAIU, latest tag `1.0.1-alpha.9` was broken due to `mix deps.get` downgrading `ex_cldr` to `2.43.2` instead of keeping the `2.44.1` pinned in `mix.lock` (as I would have expected…).
I'm concerned that this (mis)behavior may cause such error again.
More troubling, `mix hex.outdated --all` would then show that `ex_cldr` is actually updatable, so I don't know why it chose to downgrade.
Finally, AFAIU `ex_cldr`'s error was caused by to `ex_cldr-2.44` [introducing a rename](https://github.com/elixir-cldr/cldr/blame/a350c716b135b2719f67904f44a0e247aee20c68/mix/support/normalize/normalize_datetime.ex#L25).

**Comment by ju1m** [comment]
At https://github.com/bonfire-networks/bonfire-app/commit/2e189db16e7379bdda6235e107c614ca43d22a7d (ie. `ex_cldr-2.44.1`), when `MIX_ENV=prod`, I hit:
```
$ mix compile
[…]
03:02:33.060 [info] Downloaded locale :zu version v2.44.1
Generating Bonfire.Common.Localise.Cldr for 130 locales named [:af, :ar, :az, :be, :bg, ...] with a default locale named :en
Please be patient, generating functions for many locales can take some time

== Compilation error in file lib/localise/cdlr.ex ==
** (MatchError) no match of right hand side value: {:error, {Cldr.LanguageTag.ParseError, "Expected a BCP47 language tag. Could not parse the remaining \"-b\" starting at position 6"}}
    (ex_cldr 2.44.1) lib/cldr/locale/match.ex:116: anonymous fn/6 in Cldr.Locale.Match.best_match/2
    (elixir 1.18.4) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_cldr 2.44.1) lib/cldr/locale/match.ex:114: Cldr.Locale.Match.best_match/2
    (ex_cldr 2.44.1) lib/cldr/locale.ex:1943: Cldr.Locale.gettext_match/3
    (ex_cldr 2.44.1) lib/cldr/locale.ex:1882: Cldr.Locale.put_gettext_locale_name/2
    /tmp/nix-shell.NQXJpr/source/deps/bonfire_common/lib/localise/cdlr.ex:1: (file)
    /tmp/nix-shell.NQXJpr/source/deps/bonfire_common/lib/localise/cdlr.ex:1: (file)
could not compile dependency :bonfire_common, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile bonfire_common --force", update it with "mix deps.update bonfire_common" or clean it with "mix deps.clean bonfire_common"
buildPhase completed in 9 minutes 52 seconds
```
AFAIU, it's due to:

https://github.com/bonfire-networks/bonfire_common/blob/e640ebe05a850d9013de5dfcf9fbfe3b35fb5b4c/lib/localise/gettext.ex#L19-L20

Because of some gettext locales not being a valid [BCP47](https://en.wikipedia.org/wiki/IETF_language_tag) language tag, eg. `es_AR-B`:
```console
$ fd --exact-depth 1 --type directory . priv/localisation
priv/localisation/ar/
priv/localisation/bg/
priv/localisation/ca/
priv/localisation/ca_ES/
priv/localisation/de/
priv/localisation/de_CH/
priv/localisation/de_DE/
priv/localisation/en_CA/
priv/localisation/en_GB/
priv/localisation/en_SE/
priv/localisation/en_US/
priv/localisation/es/
priv/localisation/es_AR-B/
priv/localisation/es_AR-C/
priv/localisation/es_ES/
priv/localisation/es_MX/
priv/localisation/fr/
priv/localisation/fr_CA/
priv/localisation/fr_FR/
priv/localisation/gl/
priv/localisation/hr/
priv/localisation/id_ID/
priv/localisation/it/
priv/localisation/it_IT/
priv/localisation/lt/
priv/localisation/pt/
priv/localisation/pt_BR/
priv/localisation/ru/
priv/localisation/sv/
priv/localisation/vi/
priv/localisation/yue/
priv/localisation/zh/
priv/localisation/zh-Hans/
priv/localisation/zh_HK/
priv/localisation/zh_SG/
priv/localisation/zh_TW/
```

**Comment by mayel** [comment]
@ju1m we recently added more locales at https://github.com/bonfire-networks/ember/blob/main/config/ember.exs (which gets copied to `./config/ember.exs` during install, so if you could comment the ones that fail there and let us know that'd be helpful!)

**Comment by ju1m** [comment]
@mayel, 2 invalids for those in [`priv/localisation`](https://github.com/bonfire-networks/bonfire-app/tree/main/priv/localisation):
```elixir
iex> File.ls!("priv/localisation")
  |> Enum.filter(&File.dir?(Path.join("priv/localisation", &1)))
  |> Enum.map(fn tag -> {tag, Cldr.LanguageTag.Parser.parse(tag)} end)
  |> Enum.filter(fn {_, {res, _}} -> res != :ok end)
[
  {"es_AR-C",
   {:error,
    {Cldr.LanguageTag.ParseError,
     "Expected a BCP47 language tag. Could not parse the remaining \"-c\" starting at position 6"}}},
  {"es_AR-B",
   {:error,
    {Cldr.LanguageTag.ParseError,
     "Expected a BCP47 language tag. Could not parse the remaining \"-b\" starting at position 6"}}}
]
```

None for those in [config/ember.exs](https://github.com/bonfire-networks/ember/blob/main/config/ember.exs):
```elixir
iex> [ "af", "ar", "az", "be", "bg", "bn", "bo", "bs", "br", "ca", "ce", "chr", "co", "cs", "ckb", "ku", "sdh", "da", "de", "de-CH", "dz", "el", "en", "en-US", "en-GB", "en-CA", "en-SE", "eo", "es", "es-AR", "es-MX", "es-ES", "et", "eu", "fa", "fi", "fil", "fr", "fr-FR", "fr-CA", "fr-CH", "ga", "gd", "gl", "gsw", "ha", "he", "hi", "hr", "hu", "ht", "hy", "id", "is", "it", "it-IT", "it-CH", "iu", "ja", "jv", "ka", "kk", "kl", "km", "kn", "ko", "lb", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "ms", "mt", "my", "nb", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "pt-PT", "qu", "rm", "ro", "ru", "sc", "scn", "sk", "sl", "so", "sq", "sr", "st", "su", "sv", "sw", "ta", "te", "ti", "tg", "th", "tk", "to", "tr", "ts", "uk", "ug", "ur", "uz", "vi", "wo", "xh", "yi", "yo", "yue", "zh", "zh-Hant", "zh-Hant-HK", "zh-Hant-TW", "zh-Hans", "zh-Hans-SG", "zu" ]
  |> Enum.map(fn tag -> {tag, Cldr.LanguageTag.Parser.parse(tag)} end)
  |> Enum.filter(fn {_, {res, _}} -> res != :ok end)
[]
```

**Comment by mayel** [comment]
Ah thanks! I'll try to find a workaround

**Comment by mayel** [comment]
@ju1m 1.0.1-alpha.14 should have a fix for the locale issues, thanks again for your help!
