### ISSUE TITLE
Bug Report: Tailwind setup crashing

### ISSUE THREAD

**Issue by humrochagf** [bonfire-networks/bonfire-app#99]
**Describe the bug**
Hi I was trying the base setup starting from zero but when I start the dev server everything seems to go fine but the tailwind watcher is crashing leading to a non-styled webpage and this output:

```
> @0.0.0 watch.js /opt/app/assets
> esbuild ./js/bonfire_live.js ./js/bonfire_basic.js --target=es2015 --bundle --sourcemap --outdir=../priv/static/js --watch


> @0.0.0 watch.postcss /opt/app/assets
> TAILWIND_MODE=watch NODE_ENV=development postcss ./css/app.scss -o ../priv/static/css/bonfire.css -w

sh: esbuild: not found
sh: postcss: not found
 ERROR  Command failed.
 ERROR  Command failed.
[error] Task #PID<0.25003.0> started from Bonfire.Web.Endpoint terminating
** (stop) :watcher_command_error
    (phoenix 1.5.9) lib/phoenix/endpoint/watcher.ex:37: Phoenix.Endpoint.Watcher.watch/3
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["pnpm", ["watch.js"], [cd: "/opt/app/assets"]]
[error] Task #PID<0.25004.0> started from Bonfire.Web.Endpoint terminating
** (stop) :watcher_command_error
    (phoenix 1.5.9) lib/phoenix/endpoint/watcher.ex:37: Phoenix.Endpoint.Watcher.watch/3
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["pnpm", ["watch.postcss"], [cd: "/opt/app/assets"]]
[info] Running Bonfire.Web.Endpoint with cowboy 2.9.0 at :::4000 (http)
[info] Access Bonfire.Web.Endpoint at http://localhost:4000
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `export FLAVOUR=classic`
2. Run `make pre-config`
3. Add the secrets to the config file
4. Run `make setup` (without envvar to default to full docker)
5. Run `make dev`
6. After that the server spawns but already with the above output looping at the terminal
7. Opening the application I got the error saying that the cookie secret size must be at least 64 bytes long (would be great to have this info in the setup documentation)
3. Stopped the containers to fix the secret problem
4. Started it again, still the frontend asset compilation problem

**Expected behaviour**
It should start the server without crashing the assets

**Screenshots**
![bonfire](https://user-images.githubusercontent.com/1223625/126503672-1d1fcd6a-babd-4a91-ad27-d447656f3684.png)

**Desktop (please complete the following information):**
 - OS: Linux Pop-OS
 - Browser Firefox
 - Version 90.0 (64-bit)

**Comment by mayel** [comment]
Thanks for the very detailed and helpful bug report @humrochagf :smile:

I've pushed an attempted fix, could you please try again starting with `make setup`?

**Comment by humrochagf** [comment]
Unfortunately, it didn't work.

Had to do a `chown` to change the deps to my user first (I think docker generates them as root).

The only error message that I got during setup was this:

```
bash: line 1: cd: forks/bonfire_geolocate/assets: No such file or directory
ERROR: 1
make[3]: *** [Makefile:401: cmd] Error 1
make[2]: *** [Makefile:161: js.deps.install] Error 2
```

Not sure it's because the classic flavour doesn't have it, or because geolocate don't use those kinds of assets.

Just out of curiosity tried the `make update` but it doesn't fix the issue as well.

Also I didn't configured some extensions, not sure if this interfere in anything but I get this message before spawning the endpoint:

```
You have configured application :bonfire_api_graphql in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :bonfire_api_graphql exists or remove the configuration.

You have configured application :absinthe in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :absinthe exists or remove the configuration.

You have configured application :bonfire_valueflows in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :bonfire_valueflows exists or remove the configuration.

You have configured application :bonfire_fail in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :bonfire_fail exists or remove the configuration.

You have configured application :bonfire_quantify in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :bonfire_quantify exists or remove the configuration.
```

The watcher error remains the same and the build version is `v0.1.0-alpha.214`

**Comment by humrochagf** [comment]
Forgot to mention, this new version creates a `.local/state/pnpm/pnpm-state.json` that isn't in `.gitignore`

**Comment by mayel** [comment]
Ah indeed, that extension is not present in the classic flavour, I just pushed a fix to workaround that error, but that shouldn't have preventing the main app js deps from being installed. Can you please share the full output of `make js.deps.get`?

You can ignore the config warnings.

**Comment by humrochagf** [comment]
There it is:
```
ln: failed to create symbolic link 'priv/static/data/uploads': File exists
Loading environment variables from config/dev
Loading env vars from config/dev/public.env
Loading env vars from config/dev/secrets.env
Light that fire... bonfire with classic flavour in dev - 0.1.0-alpha.214 - c368b0e - flavours/classic
docker-compose up -d db search 
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
bonfire-app_db_1 is up-to-date
bonfire-app_search_1 is up-to-date
docker-compose run web bash -c "cd assets && pnpm install "
Creating bonfire-app_web_run ... done
Lockfile is up-to-date, resolution step is skipped
Packages: +323
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 WARN  EXDEV: cross-device link not permitted, link '/opt/app/.pnpm-store/v3/files/25/bfa0280f28cafc9912f4251b8c877845b521c1580e43c4f9a737066c1f85d588ba35da284207e57c3c3d0a1628dbf625820f31ce81284ca976c6ae7e1b3771' -> '/opt/app/assets/node_modules/.pnpm/mini-svg-data-uri@1.3.3/node_modules/_tmp_1_cee8e006b3cf788f540e7bb53cd83e6b/shorter-css-color-names.js'
Falling back to copying packages from store
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: /opt/app/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
 WARN  EXDEV: cross-device link not permitted, link '/opt/app/.pnpm-store/v3/files/3d/05b16dd728b42e15c731bff12dd113688a9159adba8b9cb8db60001e2e2019d3098a66fbba5704ec4106c42f3c485758891dfa6caa997a1e0db14cd0e2fced' -> '/opt/app/assets/node_modules/.pnpm/lodash.castarray@4.4.0/node_modules/_tmp_1_de7c583e2387b767d96b03bfc2573202/README.md'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/opt/app/.pnpm-store/v3/files/b7/f602a93a363a6d01b8713f0be0bf1e70c431b6c573e230ec7759e66dfe231bfa780154607b9a59f0e03322f7cedf57d2abd7a083c0f2ef2aabc8bc215bdb32' -> '/opt/app/assets/node_modules/.pnpm/lodash.isplainobject@4.0.6/node_modules/_tmp_1_8cc8aa8d83d4dccaaaf763e24524ffdb/LICENSE'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/opt/app/.pnpm-store/v3/files/73/2749c793cba9f999b5550aeda2dcbc610e53711fc68d94140989eda6e7492a0ad262b4017b22f4a93c66a995962b11459d8a739a764fd151dc4c68da15af68' -> '/opt/app/assets/node_modules/.pnpm/lodash.merge@4.6.2/node_modules/_tmp_1_9e73284aeb42f7a6e12002c559fa31a7/package.json'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/opt/app/.pnpm-store/v3/files/b7/f602a93a363a6d01b8713f0be0bf1e70c431b6c573e230ec7759e66dfe231bfa780154607b9a59f0e03322f7cedf57d2abd7a083c0f2ef2aabc8bc215bdb32' -> '/opt/app/assets/node_modules/.pnpm/lodash.uniq@4.5.0/node_modules/_tmp_1_6ddf561346f9ccac98e36e94295b109b/LICENSE'
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
 WARN  9 other warnings
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Progress: resolved 323, reused 323, downloaded 0, added 323, done
node_modules/.pnpm/esbuild@0.12.8/node_modules/esbuild: Running postinstall script, done in 99ms
node_modules/.pnpm/core-js@2.6.12/node_modules/core-js: Running postinstall script, done in 86ms

dependencies:
+ @github/details-dialog-element 3.1.2
+ @github/details-menu-element 1.0.9
+ @tailwindcss/forms 0.3.3
+ @tailwindcss/line-clamp 0.2.1
+ @tailwindcss/typography 0.4.1
+ alpinejs 2.8.2
+ nprogress 0.2.0
+ phoenix 1.5.9 <- ../deps/phoenix
+ phoenix_html 2.14.3 <- ../deps/phoenix_html
+ phoenix_live_view 0.15.7 <- ../deps/phoenix_live_view
+ tailwindcss 2.1.4

devDependencies:
+ @tailwindcss/jit 0.1.18
+ autoprefixer 10.2.6
+ cpx 1.5.0
+ esbuild 0.12.8
+ only-allow 1.0.0
+ pnpm 6.7.6
+ postcss 8.3.2
+ postcss-cli 8.3.1
+ tailwindcss-debug-screens 2.0.0
# FIXME: make generic to apply to all extensions that bundle JS
ln: failed to create symbolic link 'priv/static/data/uploads': File exists
Loading environment variables from config/dev
Loading env vars from config/dev/public.env
Loading env vars from config/dev/secrets.env
Light that fire... bonfire with classic flavour in dev - 0.1.0-alpha.214 - c368b0e - flavours/classic
docker-compose up -d db search 
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
bonfire-app_db_1 is up-to-date
bonfire-app_search_1 is up-to-date
docker-compose run web bash -c "cd forks/bonfire_geolocate/assets && pnpm install "
Creating bonfire-app_web_run ... done
bash: line 1: cd: forks/bonfire_geolocate/assets: No such file or directory
ERROR: 1
make[3]: *** [Makefile:401: cmd] Error 1
make[2]: *** [Makefile:161: js.deps.install] Error 2
ln: failed to create symbolic link 'priv/static/data/uploads': File exists
Loading environment variables from config/dev
Loading env vars from config/dev/public.env
Loading env vars from config/dev/secrets.env
Light that fire... bonfire with classic flavour in dev - 0.1.0-alpha.214 - c368b0e - flavours/classic
docker-compose up -d db search 
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
bonfire-app_db_1 is up-to-date
bonfire-app_search_1 is up-to-date
docker-compose run web bash -c "cd deps/bonfire_geolocate/assets && pnpm install "
Creating bonfire-app_web_run ... done
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
```

**Comment by mayel** [comment]
So it looks like postcss and esbuild were successfully installed (despite the warnings, looks like we need to look at how pnpm and docker can work better together), so is postcss still not running correctly?

**Comment by humrochagf** [comment]
Okay, I found the problem. The container `bonfire_web` that is the one serving the frontend and also compilling the assets isn't installing the node dependencies during the container startup.

I logged into the container with `docker exec -it bonfire_web /bin/bash` entered the `assets` folder and installed the dependencies with `pnpm install` and everything worked.

I was trying to find where the `Dockerfile` of the `bonfire_web` image is located to add this step but I'm not sure were can I find it.

**Comment by mayel** [comment]
Yeah the JS deps install is not done during docker build (for the development one: `Dockerfile.dev`, the release build is different) but by the Makefile (using the `make js.deps.get` command, which is also run as part of `make setup` and `make update`) so that JS deps can be added/updated without rebuilding the docker image.  In the logs you posted above I can see that `docker-compose run web bash -c "cd assets && pnpm install "` was executed by the makefile, which is the equivalent to what you did manually, so I'm still scratching my head...

**Comment by humrochagf** [comment]
Oh but that log is from the command `make js.deps.get` docker images are ephemeral so that this command will create a new docker container run the command close the container after it. Every time you run a `make dev` you are creating a new container, they don't reuse containers, and since `node_modules` folder is excluded from the mounted volumes, you always get an empty modules folder every run.
So to be able to have the dependencies there at the start of your application you need to have a `pnpm install` as part of `bonfire_web` dockerfile.

**Comment by mayel** [comment]
Ah that's it, good find ! I think it's a recent change that caused this. node_modules don't *have to* to be in .dockerignore but otherwise people run into permission issues when switching back and forth between WITH_DOCKER modes. 

My concern with moving the js.deps.get in the Dockerfile is that in a fresh environment the elixir deps aren't fetched at that point, so it wouldn't be possible to fetched *their* js deps. Another option could be adding a docker volume for node_modules to persist, though that wouldn't help with JS deps within extensions (unless dockerignore doesn't apply to them?).
